<?php

namespace Database\Seeders;

use App\Enums\ProductStatus;
use App\Models\Category;
use App\Models\Product;
use App\Models\Seller;
use Illuminate\Database\Seeder;

/**
 * Demo catalog: 45 products (15 per category).
 *
 * Idempotent: matched by slug, safe to re-run.
 */
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->demoProducts() as $data) {
            $category = Category::query()->where('slug', $data['category_slug'])->first();
            $seller = Seller::query()->where('slug', $data['seller_slug'])->first();

            if ($category === null || $seller === null) {
                continue;
            }

            Product::query()->updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'seller_id' => $seller->id,
                    'category_id' => $category->id,
                    'name' => $data['name'],
                    'description' => $data['description'],
                    'price' => $data['price'],
                    'stock' => $data['stock'],
                    'weight_grams' => $data['weight_grams'],
                    'status' => ProductStatus::Active,
                ]
            );
        }
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    protected function demoProducts(): array
    {
        return [
            // --- Keripik (Ahmad Kerepek) ---
            [
                'name' => 'Keripik Pisang Original',
                'slug' => 'keripik-pisang-original',
                'description' => 'Keripik pisang renyah original, 250g.',
                'price' => '25.50',
                'stock' => 100,
                'weight_grams' => 250,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Singkong Balado',
                'slug' => 'keripik-singkong-balado',
                'description' => 'Keripik singkong balado pedas manis, 250g.',
                'price' => '22.00',
                'stock' => 80,
                'weight_grams' => 250,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Ubi Pedas Manis',
                'slug' => 'keripik-ubi-pedas-manis',
                'description' => 'Keripik ubi keledek pedas manis, rangup dan berempah, 250g.',
                'price' => '23.50',
                'stock' => 90,
                'weight_grams' => 250,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Pisang Coklat',
                'slug' => 'keripik-pisang-coklat',
                'description' => 'Keripik pisang salutan coklat premium, kegemaran anak-anak, 200g.',
                'price' => '28.00',
                'stock' => 75,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Tempe Original',
                'slug' => 'keripik-tempe-original',
                'description' => 'Keripik tempe nipis rangup dengan perasa bawang putih, 200g.',
                'price' => '20.00',
                'stock' => 110,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Pisang Keju',
                'slug' => 'keripik-pisang-keju',
                'description' => 'Keripik pisang bertabur serbuk keju yang gurih, 200g.',
                'price' => '27.00',
                'stock' => 65,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Singkong Original',
                'slug' => 'keripik-singkong-original',
                'description' => 'Keripik singkong original gurih dengan taburan garam laut, 250g.',
                'price' => '19.50',
                'stock' => 120,
                'weight_grams' => 250,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Pisang Manis',
                'slug' => 'keripik-pisang-manis',
                'description' => 'Keripik pisang raja manis legit tanpa pengawet, 250g.',
                'price' => '24.00',
                'stock' => 85,
                'weight_grams' => 250,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Ubi Ungu',
                'slug' => 'keripik-ubi-ungu',
                'description' => 'Keripik ubi ungu manis semulajadi, warna menarik, 200g.',
                'price' => '26.50',
                'stock' => 70,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Kentang Balado',
                'slug' => 'keripik-kentang-balado',
                'description' => 'Keripik kentang nipis bersalut sambal balado, 200g.',
                'price' => '24.50',
                'stock' => 95,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Pisang Pedas',
                'slug' => 'keripik-pisang-pedas',
                'description' => 'Keripik pisang pedas berapi untuk pencinta cabai, 200g.',
                'price' => '25.00',
                'stock' => 60,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Singkong Keju',
                'slug' => 'keripik-singkong-keju',
                'description' => 'Keripik singkong premium bersalut serbuk keju cheddar, 200g.',
                'price' => '26.00',
                'stock' => 78,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Talas Original',
                'slug' => 'keripik-talas-original',
                'description' => 'Keripik talas rangup dengan aroma keladi yang wangi, 200g.',
                'price' => '23.00',
                'stock' => 88,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Ubi Coklat',
                'slug' => 'keripik-ubi-coklat',
                'description' => 'Keripik ubi manis bersalut coklat susu, 200g.',
                'price' => '29.00',
                'stock' => 55,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            [
                'name' => 'Keripik Pisang Salted Egg',
                'slug' => 'keripik-pisang-salted-egg',
                'description' => 'Keripik pisang salted egg viral, lemak berkrim, 200g.',
                'price' => '32.00',
                'stock' => 50,
                'weight_grams' => 200,
                'category_slug' => 'keripik',
                'seller_slug' => 'ahmad-kerepek',
            ],
            // --- Hijab (Siti Modest) ---
            [
                'name' => 'Hijab Paris Premium',
                'slug' => 'hijab-paris-premium',
                'description' => 'Hijab paris premium bahan adem, ukuran 110x110.',
                'price' => '45.00',
                'stock' => 50,
                'weight_grams' => 120,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Kaos Basic',
                'slug' => 'pashmina-kaos-basic',
                'description' => 'Pashmina kaos basic, 180x70 cm.',
                'price' => '35.00',
                'stock' => 60,
                'weight_grams' => 180,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Voal Motif Bunga',
                'slug' => 'hijab-voal-motif-bunga',
                'description' => 'Hijab voal ultrafine motif bunga eksklusif, mudah dibentuk, 115x115 cm.',
                'price' => '52.00',
                'stock' => 40,
                'weight_grams' => 130,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Ceruty Babydoll',
                'slug' => 'pashmina-ceruty-babydoll',
                'description' => 'Pashmina ceruty babydoll flowy dengan tekstur pasir lembut, 175x75 cm.',
                'price' => '42.00',
                'stock' => 55,
                'weight_grams' => 200,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Instant Sport',
                'slug' => 'hijab-instant-sport',
                'description' => 'Hijab instant sport bahan dry-fit, selesa untuk aktiviti harian, free size.',
                'price' => '38.00',
                'stock' => 70,
                'weight_grams' => 150,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Plisket Premium',
                'slug' => 'pashmina-plisket-premium',
                'description' => 'Pashmina plisket premium yang tidak mudah kusut, 180x75 cm.',
                'price' => '48.00',
                'stock' => 45,
                'weight_grams' => 190,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Bella Square',
                'slug' => 'hijab-bella-square',
                'description' => 'Hijab bella square best seller, tidak licin dan tegak di dahi, 115x115 cm.',
                'price' => '29.00',
                'stock' => 100,
                'weight_grams' => 140,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Diamond Crepe',
                'slug' => 'pashmina-diamond-crepe',
                'description' => 'Pashmina diamond italiano dengan tekstur kulit jeruk, 175x75 cm.',
                'price' => '44.00',
                'stock' => 48,
                'weight_grams' => 210,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Instant Jersey',
                'slug' => 'hijab-instant-jersey',
                'description' => 'Hijab instant jersey antem, praktis tanpa jarum, free size.',
                'price' => '33.00',
                'stock' => 82,
                'weight_grams' => 160,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Motif Abstrak',
                'slug' => 'hijab-motif-abstrak',
                'description' => 'Hijab voal motif abstrak moden, warna pastel eksklusif, 115x115 cm.',
                'price' => '55.00',
                'stock' => 35,
                'weight_grams' => 130,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Sifon Polos',
                'slug' => 'pashmina-sifon-polos',
                'description' => 'Pashmina sifon polos ringan dengan tepi neci kemas, 175x70 cm.',
                'price' => '36.00',
                'stock' => 66,
                'weight_grams' => 150,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Paris Polos',
                'slug' => 'hijab-paris-polos',
                'description' => 'Hijab paris polos harian, puluhan pilihan warna, 110x110 cm.',
                'price' => '22.00',
                'stock' => 150,
                'weight_grams' => 110,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Crinkle Premium',
                'slug' => 'hijab-crinkle-premium',
                'description' => 'Hijab crinkle air flow premium, ironless dan adem, 120x120 cm.',
                'price' => '39.00',
                'stock' => 58,
                'weight_grams' => 140,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Pashmina Kaos Oversize',
                'slug' => 'pashmina-kaos-oversize',
                'description' => 'Pashmina kaos oversize menutup dada, bahan stretch nyaman, 200x75 cm.',
                'price' => '46.00',
                'stock' => 42,
                'weight_grams' => 230,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            [
                'name' => 'Hijab Satin Silk',
                'slug' => 'hijab-satin-silk',
                'description' => 'Hijab satin silk mewah dengan kilau elegan untuk majlis khas, 115x115 cm.',
                'price' => '58.00',
                'stock' => 30,
                'weight_grams' => 150,
                'category_slug' => 'hijab',
                'seller_slug' => 'siti-modest',
            ],
            // --- Kerudung (Aina Collection) ---
            [
                'name' => 'Kerudung Bergo Maryam',
                'slug' => 'kerudung-bergo-maryam',
                'description' => 'Kerudung bergo tali, bahan jersey premium.',
                'price' => '28.00',
                'stock' => 70,
                'weight_grams' => 160,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Segi Empat Voal',
                'slug' => 'kerudung-segi-empat-voal',
                'description' => 'Kerudung segi empat voal ultrafine, 110x110.',
                'price' => '32.50',
                'stock' => 65,
                'weight_grams' => 120,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Bergo Hamimah',
                'slug' => 'kerudung-bergo-hamimah',
                'description' => 'Kerudung bergo pet antem bahan kaos pe, selesa dipakai seharian.',
                'price' => '30.00',
                'stock' => 80,
                'weight_grams' => 170,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Segi Empat Polos',
                'slug' => 'kerudung-segi-empat-polos',
                'description' => 'Kerudung segi empat polos bahan double hycount, warna pekat, 115x115 cm.',
                'price' => '26.00',
                'stock' => 95,
                'weight_grams' => 130,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Pashmina Inner',
                'slug' => 'kerudung-pashmina-inner',
                'description' => 'Pashmina dengan inner menyatu, praktis dan kemas, 175x70 cm.',
                'price' => '40.00',
                'stock' => 50,
                'weight_grams' => 210,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Anak Karakter',
                'slug' => 'kerudung-anak-karakter',
                'description' => 'Kerudung anak bahan jersey lembut dengan aksen renda, saiz S dan M.',
                'price' => '18.50',
                'stock' => 120,
                'weight_grams' => 90,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Bergo Sport',
                'slug' => 'kerudung-bergo-sport',
                'description' => 'Kerudung bergo sport bahan dry-fit dengan lubang earphone, free size.',
                'price' => '34.00',
                'stock' => 62,
                'weight_grams' => 150,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Segi Empat Motif',
                'slug' => 'kerudung-segi-empat-motif',
                'description' => 'Kerudung segi empat motif bunga manis bahan katun voal, 115x115 cm.',
                'price' => '36.50',
                'stock' => 54,
                'weight_grams' => 135,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Pashmina Ceruty',
                'slug' => 'kerudung-pashmina-ceruty',
                'description' => 'Pashmina ceruty dengan detail renda tepi, anggun dan flowy, 175x75 cm.',
                'price' => '47.00',
                'stock' => 38,
                'weight_grams' => 205,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Bergo Renda',
                'slug' => 'kerudung-bergo-renda',
                'description' => 'Kerudung bergo dengan aksen renda cantik di bahagian muka, bahan jersey.',
                'price' => '37.00',
                'stock' => 46,
                'weight_grams' => 170,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Segi Empat Satin',
                'slug' => 'kerudung-segi-empat-satin',
                'description' => 'Kerudung segi empat satin velvet kilau mewah untuk majlis, 115x115 cm.',
                'price' => '49.00',
                'stock' => 32,
                'weight_grams' => 145,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Instant Zipper',
                'slug' => 'kerudung-instant-zipper',
                'description' => 'Kerudung instant zipper belakang, kemas tanpa lilit, bahan moscrepe.',
                'price' => '35.00',
                'stock' => 68,
                'weight_grams' => 165,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Bergo Anak',
                'slug' => 'kerudung-bergo-anak',
                'description' => 'Kerudung bergo anak bahan kaos lembut, senang dipakai sekolah, saiz S dan M.',
                'price' => '16.00',
                'stock' => 140,
                'weight_grams' => 80,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Pashmina Plisket',
                'slug' => 'kerudung-pashmina-plisket',
                'description' => 'Pashmina plisket lidi yang kemas dan tidak perlu gosok, 180x75 cm.',
                'price' => '43.00',
                'stock' => 44,
                'weight_grams' => 195,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
            [
                'name' => 'Kerudung Segi Empat Syari',
                'slug' => 'kerudung-segi-empat-syari',
                'description' => 'Kerudung segi empat syari jumbo menutup dada, bahan ceruty, 130x130 cm.',
                'price' => '44.50',
                'stock' => 52,
                'weight_grams' => 180,
                'category_slug' => 'kerudung',
                'seller_slug' => 'aina-collection',
            ],
        ];
    }
}
