<script setup lang="ts">
import { Head, Link, router } from '@inertiajs/vue3';
import { onMounted, reactive, ref } from 'vue';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { index } from '@/routes/seller/products';
import RichTextEditor from '@/components/RichTextEditor.vue';

type Product = { id: number; name: string; description?: string | null; price: string | number; stock: number; weight_grams: number; status: string; category?: { id: number } | null; images?: { id: number; url: string }[] };
type Category = { id: number; name: string };
const props = defineProps<{ product: Product }>();
const form = reactive({ name: props.product.name, description: props.product.description ?? '', price: String(props.product.price), stock: String(props.product.stock), weight_grams: String(props.product.weight_grams), status: props.product.status, category_id: String(props.product.category?.id ?? '') });
const categories = ref<Category[]>([]); const errors = ref<Record<string, string>>({}); const isSaving = ref(false); const images = ref<File[]>([]); const removeImageIds = ref<number[]>([]);
onMounted(async () => { const response = await fetch('/api/v1/categories', { headers: { Accept: 'application/json' } }); if (response.ok) categories.value = ((await response.json()) as { data: Category[] }).data; });
function csrfToken(): string { return (document.querySelector('meta[name="csrf-token"]') as HTMLMetaElement | null)?.content ?? ''; }
function onFiles(event: Event): void { images.value = Array.from((event.target as HTMLInputElement).files ?? []); }
async function save(): Promise<void> { isSaving.value = true; errors.value = {}; const data = new FormData(); data.append('_method', 'PUT'); for (const [key, value] of Object.entries(form)) data.append(key, value); for (const image of images.value) data.append('images[]', image); for (const id of removeImageIds.value) data.append('remove_image_ids[]', String(id)); const response = await fetch(`/api/v1/seller/products/${props.product.id}`, { method: 'POST', credentials: 'same-origin', headers: { Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest', 'X-CSRF-TOKEN': csrfToken() }, body: data }); if (response.ok) { router.visit(index()); return; } const body = (await response.json()) as { errors?: Record<string, string[]> }; for (const [field, messages] of Object.entries(body.errors ?? {})) errors.value[field] = messages[0] ?? 'Invalid value.'; isSaving.value = false; }
</script>

<template>
    <Head :title="`Edit ${product.name}`" />
    <div class="flex h-full flex-1 flex-col gap-4 p-4"><Link :href="index()" class="text-muted-foreground w-fit text-sm hover:underline">← Back to products</Link><Heading variant="small" :title="`Edit ${product.name}`" description="Update product owned by your store." /><form class="max-w-2xl space-y-5 rounded-xl border p-4" @submit.prevent="save"><div class="grid gap-2"><Label for="name">Name</Label><Input id="name" v-model="form.name" required /><InputError :message="errors.name" /></div><div class="grid gap-2"><Label for="description">Description</Label><RichTextEditor v-model="form.description"/><InputError :message="errors.description" /></div><div class="grid grid-cols-2 gap-4"><div class="grid gap-2"><Label for="price">Price</Label><Input id="price" v-model="form.price" type="number" min="0" step="0.01" required /><InputError :message="errors.price" /></div><div class="grid gap-2"><Label for="stock">Stock</Label><Input id="stock" v-model="form.stock" type="number" min="0" required /><InputError :message="errors.stock" /></div></div><div class="grid grid-cols-2 gap-4"><div class="grid gap-2"><Label for="category_id">Category</Label><select id="category_id" v-model="form.category_id" required class="border-input h-9 rounded-md border bg-transparent px-3 text-sm"><option v-for="category in categories" :key="category.id" :value="category.id">{{ category.name }}</option></select><InputError :message="errors.category_id" /></div><div class="grid gap-2"><Label for="status">Status</Label><select id="status" v-model="form.status" class="border-input h-9 rounded-md border bg-transparent px-3 text-sm"><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select><InputError :message="errors.status" /></div></div><div class="grid gap-2"><Label for="weight_grams">Weight (grams)</Label><Input id="weight_grams" v-model="form.weight_grams" type="number" min="0" required /><InputError :message="errors.weight_grams" /></div><div class="grid gap-2"><Label for="images">Add images</Label><Input id="images" type="file" accept="image/jpeg,image/png,image/webp" multiple @change="onFiles" /><InputError :message="errors.images" /></div><div v-if="product.images?.length" class="flex flex-wrap gap-2"><div v-for="image in product.images" :key="image.id" class="relative"><img :src="image.url" class="h-20 w-20 rounded border object-cover" /><button type="button" class="text-destructive text-xs hover:underline" @click="removeImageIds.includes(image.id) ? removeImageIds = removeImageIds.filter((id) => id !== image.id) : removeImageIds.push(image.id)">{{ removeImageIds.includes(image.id) ? 'Undo' : 'Remove' }}</button></div></div><Button type="submit" :disabled="isSaving">{{ isSaving ? 'Saving…' : 'Save product' }}</Button></form></div>
</template>
